#!/usr/bin/env python3
"""
Generate a Markdown index of Canopy's deployed packages from the on-chain data
that fetch-canopy-source.py writes. Output is GitHub-README-safe: no scripts,
no styles, only markup GitHub's sanitizer keeps.

    python3 tools/fetch-canopy-source.py      # writes canopy-source/manifest.json
    python3 tools/gen-package-index.py        # prints Markdown to stdout
"""

import json
import sys
from pathlib import Path

EXPLORER = "https://explorer.movementnetwork.xyz"
MANIFEST = Path("canopy-source/manifest.json")

# Presentation order and human labels; keyed by the label the fetch tool uses.
TIERS = [
    ("Router",         ["router"]),
    ("Core",           ["core"]),
    ("Strategies",     ["strategy-echelon-simple", "strategy-moveposition-simple",
                        "strategy-layerbank-simple", "strategy-meridian-rewards",
                        "strategy-placeholder-simple"]),
    ("Venue adapters", ["block-echelon", "block-moveposition", "block-layerbank",
                        "block-meridian-farming", "block-layerbank-airdrop",
                        "block-placeholder"]),
    ("Rewards",        ["rewards", "rewards-batcher", "rewards-std-batcher"]),
    ("Views & helpers",["helpers", "views"]),
]


def main():
    if not MANIFEST.exists():
        sys.exit(f"{MANIFEST} not found — run tools/fetch-canopy-source.py first")
    pkgs = {p["label"]: p for p in json.loads(MANIFEST.read_text())}

    out = []
    for tier, labels in TIERS:
        rows = []
        for label in labels:
            p = pkgs.get(label)
            if p is None:
                continue
            addr = p["address"]
            mods = " · ".join(
                f"[`{m}`]({EXPLORER}/object/{addr}/modules/code/{m})" for m in p["modules"]
            )
            rows.append(f"| **{p['package']}** | {mods} | [`{addr[:10]}…`]({EXPLORER}/account/{addr}) |")
        if rows:
            out.append(f"**{tier}**\n")
            out.append("| Package | Modules | Address |")
            out.append("|---|---|---|")
            out.extend(rows)
            out.append("")

    n_pkg = sum(1 for t, ls in TIERS for l in ls if l in pkgs)
    n_mod = sum(len(pkgs[l]["modules"]) for t, ls in TIERS for l in ls if l in pkgs)
    print(f"<!-- generated by tools/gen-package-index.py — {n_pkg} packages, {n_mod} modules -->")
    print("\n".join(out).rstrip())


if __name__ == "__main__":
    main()
